### ISSUE TITLE
As an admin I want a page for Admins to upload new challenges

### ISSUE THREAD

**Issue by DungLe2911** [acasi-ctf/ctf#122]
Admin should be able to upload new challenges be loading document from local. This will be done through an uploading page.

# Tasks:
- [x] Show link to new page on sidebar if the admin is a user.
- [x] Have both a choose file and submit button.
- [x] Give the administrator feedback whether it was posted successfully or failed.

**Comment by DungLe2911** [comment]
Currently, we have a function to fetch information from server but we dont have anything to do the API post request. Need help on create a function to do that.

**Comment by DungLe2911** [comment]
Tasks:
- [] Modify API post so it works with ZIP files. At the moment, this is only intented for JSON
- [] Integrate post API to page for creat new challenge
