### ISSUE TITLE
As a user I would like a polished ciphers challenge set with easy to read documentation and an easy to identify flag so that I can have a more intuitive experience.

### ISSUE THREAD

**Issue by lgorence** [acasi-ctf/ctf#181]
This task is to polish up the ciphers challenge set.

# Subtasks
- [ ] Edit documentation for clarity, ensure it has all of the "actions" that the user must be able to do. @colbycocking
- [x] Edit source code to ensure that the flag is clearly printed once the challenge is completed. @EllisHZH
  - [x] Ensure the user can't access the flag without some prerequisite knowledge. If the challenge must have the value in plain text, mask it with base64 or something similar. @EllisHZH
  - [x] Add the flag to the challenge JSON (see challenges/pentesting/strings for example, if you have questions ask @lgorence)
- [x] Play through each challenge to ensure that it flows correctly and it is possible to complete.
