### ISSUE TITLE
Polish pentesting challenge set

### ISSUE THREAD

**Issue by lgorence** [acasi-ctf/ctf#182]
This task is to polish up the pentesting challenge set.

# Subtasks
- [ ] Edit documentation for clarity, ensure it has all of the "actions" that the user must be able to do.
- [ ] Edit source code to ensure that the flag is clearly printed once the challenge is completed.
- [ ] Ensure the user can't access the flag without some prerequisite knowledge. If the challenge must have the value in plain text, mask it with base64 or something similar.

**Comment by colbycocking** [comment]
@EthanIsakson where did you land with this?

**Comment by EthanIsakson** [comment]
Reread all documentation for Challenges and Penetration Testing. Added all flags to JSON under #216.

Still working through some issues with our Password Cracking tutorials. Encountered an issue with Hash-Identifier not having needed python module, which is odd because it ran in a container locally. Updated Dockerfile to install pip and the module which should resolve the issue.

Still working through issues trying to get adequate drivers onto the Hashcat image so that it can run hashcat like I could locally.
